[package]
name = "riker"
version = "0.3.0"
authors = ["Lee Smith <lee@riker.rs>"]
edition = "2018"
description = "Easily build fast, highly concurrent and resilient applications. An Actor Framework for Rust."
homepage = "https://riker.rs"
repository = "https://github.com/riker-rs/riker"
license = "MIT"
readme = "README.md"
keywords = ["actors", "actor-model", "async", "cqrs", "event_sourcing"]

[badges]
travis-ci = { repository = "riker-rs/riker" }

[features]
default = ["interact_support"]
interact_support = ["interact"]

[dependencies]
riker-macros = { path = "riker-macros", version = "0.1" }
bytes = "0.4"
chrono = "0.4"
config = "0.9"
futures-preview = "0.3.0-alpha.16"
log = { version = "0.4", features = ["std"] }
rand = "0.4"
regex = "0.2"
runtime-fmt = "0.3.0"
uuid = { version = "0.6", features = ["v4"] }
pin-utils = "0.1.0-alpha.4"

interact = { version = "0.3.5", optional = true }


[dev-dependencies]
riker-testkit = "0.1.0"
